

> *Numpy - Numerical Python*



Advantages of Numpy Arrays
- Allows several Mathematical Operations
- Faster Operations

In [ ]:
!pip install numpy

In [1]:
import numpy as np



> *Numpy Arrays*



In [ ]:
# List
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Numpy Array => Matrix

In [ ]:
# Creating a 1-Dimensional Numpy Array
np_array_1d = np.array([1, 2, 3, 4])
print(np_array_1d)

[1 2 3 4]


In [ ]:
print(np_array_1d.shape)

(4,)


In [ ]:
# 2-Dimensional Numpy Array
np_array_2d = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(np_array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(np_array_2d.shape)

(2, 4)


In [ ]:
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)], dtype=float)
print(a)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
b = np.array([1, 2 , 3, 4], dtype=float)
print(b)

[1. 2. 3. 4.]


- Initial Placeholders in Numpy Arrays

In [ ]:
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.zeros((3, 3), dtype=int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
y1 = np.ones((3, 3), dtype=int)
print(y1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Creating a Numpy Array of a particular Value
a1 = np.full((5, 4), 7)
print(a1)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# Creating an Identity Matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
k1 = np.eye(3, dtype=int)
print(k1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Creating a Numpy Array with Random values
r = np.random.random((3, 4))
print(r)

[[0.40319885 0.12348788 0.59029221 0.82839725]
 [0.26747769 0.92729783 0.37340345 0.04470887]
 [0.17554523 0.59179098 0.32269997 0.72793482]]


In [ ]:
# Creating a Random Integer values numpy array within a specific range
# Range of elements in the Numpy Array -> Range = [startPoint, endPoint)
r1 = np.random.randint(1, 100, (3, 5))
print(r1)

[[47 85 86 36 12]
 [68 63 16 99 76]
 [10 82  7 49 82]]


In [ ]:
r2 = np.random.randint(1, 5, (3, 3))
print(r2)

[[4 4 1]
 [4 2 1]
 [4 2 2]]


In [ ]:
# Numpy array of evenly spaced values
# np.linspace(startPoint, endPoint, No.of Elements Required)
d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]


In [3]:
# Range of elements in the Numpy Array -> Range = [startPoint, endPoint)
# np.linspace(startPoint, endPoint, No.of Elements)
# np.linspace() -> Creates a Numpy array with given No.of elements required
# np.linspace() -> Difference between consecutive elements in the Numpy Array is Same
d1 = np.linspace(10, 30, 5)
print(d1)

[10. 15. 20. 25. 30.]


In [4]:
# In the above example the difference between the consecutive elements in the Numpy array is Same
# 15-10 = 5
# 20-15 = 5
# 25-20 = 5
# 30-25 = 5

In [6]:
# Creating a Numpy Array By providing a 'Step Value' to the elements of the array
# np.arange(startPoint, endPoint, stepValue)
d2 = np.arange(10, 30, 5)
print(d2)

[10 15 20 25]


In [ ]:
# Converting a List into a Numpy Array
list2 = [10, 20, 30, 40, 50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

- Converting a List into a Tuple => tuple()
- Converting a List into a Set => set()
- Converting a List into a Numpy Array => np.asarray()



> ***Analysing a Numpy Array***



In [7]:
numpy_array = np.random.randint(10, 90, (5, 5))
print(numpy_array)

[[48 66 33 16 56]
 [41 25 67 15 38]
 [81 36 45 60 74]
 [33 27 10 75 46]
 [41 20 16 53 50]]


In [8]:
# Array Dimension -> numpy_array.shape -> returns a tuple => (rows, cols)
print(numpy_array.shape)

(5, 5)


In [9]:
# No.of Dimensions
print(numpy_array.ndim)

2


In [10]:
# No.of elements of a Numpy Array
print(numpy_array.size)

25


In [11]:
# Checking the Data Type of the elements in the Numpy Array
print(numpy_array.dtype)

int64




> *Mathematical Operations On a Numpy Array*



In [12]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2)    # Concatenate or Joins two Lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

In [14]:
print(a)
print(b)

[[1 9 5]
 [8 6 9]
 [2 3 7]]
[[18 14 12]
 [15 14 16]
 [11 16 15]]


In [15]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# Here the above Mathematical Operations Is Performed between the Corressponding Elements of the 2 Matrices (Numpy Arrays)
# For a*b => Matrix Multiplication is Not performed => a*b => Multiplication is performed between the Corressponding Elements Of the 2 Numpy Arrays


[[19 23 17]
 [23 20 25]
 [13 19 22]]
[[-17  -5  -7]
 [ -7  -8  -7]
 [ -9 -13  -8]]
[[ 18 126  60]
 [120  84 144]
 [ 22  48 105]]
[[0.05555556 0.64285714 0.41666667]
 [0.53333333 0.42857143 0.5625    ]
 [0.18181818 0.1875     0.46666667]]


In [16]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

print(a)
print(b)

[[9 9 2]
 [6 7 1]
 [5 0 9]]
[[16 15 19]
 [10 19 17]
 [17 18 10]]


In [17]:
print(np.add(a, b))         # a+b
print(np.subtract(a, b))    # a-b
print(np.multiply(a, b))    # a*b
print(np.divide(a, b))      # a/b

[[25 24 21]
 [16 26 18]
 [22 18 19]]
[[ -7  -6 -17]
 [ -4 -12 -16]
 [-12 -18  -1]]
[[144 135  38]
 [ 60 133  17]
 [ 85   0  90]]
[[0.5625     0.6        0.10526316]
 [0.6        0.36842105 0.05882353]
 [0.29411765 0.         0.9       ]]


In [18]:
# np.multiply(a, b)  => Here Matrix Multiplication will not be takes place
# np.multiply() => Multiplication is performed between Corressponding Elements of the 2 Numpy Arrays



> ***Numpy Array => Matrix***



In [20]:
A = np.random.randint(0, 10, (2, 3))
print(A)
print(A.shape)

[[9 8 9]
 [9 6 5]]
(2, 3)




> *Transpose Of a Numpy Array*
- Method 1 ->  *np.transpose(np_array)*
- Method 2 ->  *np_array.T*




In [21]:
# Transpose of a Numpy Array (Matrix)
A_transpose = np.transpose(A)
print(A_transpose)
print(A_transpose.shape)

[[9 9]
 [8 6]
 [9 5]]
(3, 2)


In [22]:
# Transpose of a Numpy Array
A_transpose1 = A.T
print(A_transpose1)
print(A_transpose1.shape)

[[9 9]
 [8 6]
 [9 5]]
(3, 2)




> ***Re-Shaping** a Numpy Array*



In [2]:
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[8 6 3]
 [6 3 1]]
(2, 3)


In [3]:
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[8 6]
 [3 6]
 [3 1]]
(3, 2)
